/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AdminWhoamiRouteImport } from './routes/admin.whoami'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhoamiRoute = AdminWhoamiRouteImport.update({
  id: '/whoami',
  path: '/whoami',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/planner': typeof PlannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/whoami': typeof AdminWhoamiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/planner': typeof PlannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/whoami': typeof AdminWhoamiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/planner': typeof PlannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/whoami': typeof AdminWhoamiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/planner'
    | '/sitemap.xml'
    | '/admin/new'
    | '/admin/whoami'
    | '/projects/$slug'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/planner'
    | '/sitemap.xml'
    | '/admin/new'
    | '/admin/whoami'
    | '/projects/$slug'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/planner'
    | '/sitemap.xml'
    | '/admin/new'
    | '/admin/whoami'
    | '/projects/$slug'
    | '/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  PlannerRoute: typeof PlannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whoami': {
      id: '/admin/whoami'
      path: '/whoami'
      fullPath: '/admin/whoami'
      preLoaderRoute: typeof AdminWhoamiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNewRoute: typeof AdminNewRoute
  AdminWhoamiRoute: typeof AdminWhoamiRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewRoute: AdminNewRoute,
  AdminWhoamiRoute: AdminWhoamiRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  PlannerRoute: PlannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
